export const SPENDING_CATEGORIES = [
  'groceries',
  'dining',
  'online_shopping',
  'fuel',
  'utilities',
  'entertainment',
  'travel',
  'healthcare',
  'education',
  'insurance',
  'rent',
  'emi',
  'investments',
  'shopping',
  'electronics',
  'fashion',
  'beauty',
  'fitness',
  'subscriptions',
  'transportation',
  'gifts',
  'charity',
  'other',
] as const;

export type SpendingCategory = (typeof SPENDING_CATEGORIES)[number];

// Human-readable labels for categories
export const CATEGORY_LABELS: Record<SpendingCategory, string> = {
  groceries: 'Groceries',
  dining: 'Dining & Restaurants',
  online_shopping: 'Online Shopping',
  fuel: 'Fuel & Gas',
  utilities: 'Utilities & Bills',
  entertainment: 'Entertainment',
  travel: 'Travel & Hotels',
  healthcare: 'Healthcare & Medical',
  education: 'Education',
  insurance: 'Insurance',
  rent: 'Rent',
  emi: 'EMI Payments',
  investments: 'Investments',
  shopping: 'Shopping',
  electronics: 'Electronics',
  fashion: 'Fashion & Apparel',
  beauty: 'Beauty & Personal Care',
  fitness: 'Fitness & Wellness',
  subscriptions: 'Subscriptions',
  transportation: 'Transportation',
  gifts: 'Gifts',
  charity: 'Charity & Donations',
  other: 'Other',
};

// Category icons (for UI, optional)
export const CATEGORY_ICONS: Record<SpendingCategory, string> = {
  groceries: '🛒',
  dining: '🍽️',
  online_shopping: '🛍️',
  fuel: '⛽',
  utilities: '💡',
  entertainment: '🎬',
  travel: '✈️',
  healthcare: '🏥',
  education: '📚',
  insurance: '🛡️',
  rent: '🏠',
  emi: '💳',
  investments: '📈',
  shopping: '🛒',
  electronics: '📱',
  fashion: '👔',
  beauty: '💄',
  fitness: '💪',
  subscriptions: '📺',
  transportation: '🚗',
  gifts: '🎁',
  charity: '❤️',
  other: '📦',
};
