-- CardSense canonical card catalog. Safe to rerun.
begin;

-- Add every canonical catalog field before the import. This also upgrades
-- projects that still have the older credit_cards table shape.
alter table public.credit_cards
  add column if not exists bank_name text,
  add column if not exists card_network text,
  add column if not exists card_variant text,
  add column if not exists image_url text,
  add column if not exists joining_fee integer default 0,
  add column if not exists annual_fee_waiver_spend integer,
  add column if not exists renewal_fee integer,
  add column if not exists min_income_salaried integer,
  add column if not exists min_income_self_employed integer,
  add column if not exists min_income_required integer,
  add column if not exists min_cibil_score integer,
  add column if not exists min_credit_score integer,
  add column if not exists min_age integer default 18,
  add column if not exists max_age integer default 65,
  add column if not exists requires_itr boolean default false,
  add column if not exists requires_existing_relationship boolean default false,
  add column if not exists reward_rate_default numeric(10, 4),
  add column if not exists reward_rate_categories jsonb default '{}'::jsonb,
  add column if not exists welcome_benefits jsonb default '{}'::jsonb,
  add column if not exists milestone_benefits jsonb default '{}'::jsonb,
  add column if not exists lounge_access text,
  add column if not exists lounge_access_details text,
  add column if not exists lounge_visits_per_quarter integer,
  add column if not exists fuel_surcharge_waiver boolean default false,
  add column if not exists fuel_surcharge_waiver_cap integer,
  add column if not exists movie_benefits text,
  add column if not exists dining_benefits text,
  add column if not exists travel_insurance_cover integer,
  add column if not exists purchase_protection_cover integer,
  add column if not exists golf_access boolean default false,
  add column if not exists concierge_service boolean default false,
  add column if not exists forex_markup numeric(8, 4),
  add column if not exists emi_conversion_available boolean default true,
  add column if not exists description text,
  add column if not exists pros text[] default '{}'::text[],
  add column if not exists cons text[] default '{}'::text[],
  add column if not exists best_for text[] default '{}'::text[],
  add column if not exists apply_url text,
  add column if not exists is_active boolean default true,
  add column if not exists popularity_score integer default 0,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.credit_cards
  add column if not exists card_slug text,
  add column if not exists data_source text not null default 'catalog_import',
  add column if not exists data_last_verified_at timestamptz,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table public.credit_cards
  drop constraint if exists credit_cards_card_type_check;

alter table public.credit_cards
  add constraint credit_cards_card_type_check
  check (
    card_type is null
    or card_type in (
      'entry_level', 'premium', 'super_premium', 'business', 'fuel',
      'cashback', 'rewards', 'travel', 'shopping', 'lifestyle', 'secured'
    )
  ) not valid;

update public.credit_cards
set card_slug = trim(both '-' from regexp_replace(
  lower(concat(coalesce(bank_name, 'card'), '-', coalesce(card_name, ''))),
  '[^a-z0-9]+', '-', 'g'
))
where card_slug is null or btrim(card_slug) = '';

with duplicate_slugs as (
  select id, card_slug,
    row_number() over (partition by card_slug order by created_at nulls first, id) as slug_rank
  from public.credit_cards
  where card_slug is not null
)
update public.credit_cards cards
set card_slug = cards.card_slug || '-' || left(cards.id::text, 8)
from duplicate_slugs duplicates
where cards.id = duplicates.id
  and duplicates.slug_rank > 1;

alter table public.credit_cards alter column card_slug set not null;

create unique index if not exists credit_cards_card_slug_key
  on public.credit_cards (card_slug);

create index if not exists credit_cards_active_popularity_idx
  on public.credit_cards (is_active, popularity_score desc);

create index if not exists credit_cards_search_idx
  on public.credit_cards using gin (
    to_tsvector(
      'simple'::regconfig,
      coalesce(bank_name, '') || ' ' || coalesce(card_name, '') || ' ' || coalesce(description, '')
    )
  );

insert into public.credit_cards (card_slug, bank_name, card_name, card_network, card_type, card_variant, image_url, joining_fee, annual_fee, annual_fee_waiver_spend, renewal_fee, min_income_salaried, min_income_self_employed, min_income_required, min_cibil_score, min_credit_score, min_age, max_age, requires_itr, requires_existing_relationship, reward_rate_default, reward_rate_categories, welcome_benefits, milestone_benefits, lounge_access, lounge_access_details, lounge_visits_per_quarter, fuel_surcharge_waiver, fuel_surcharge_waiver_cap, movie_benefits, dining_benefits, travel_insurance_cover, purchase_protection_cover, golf_access, concierge_service, forex_markup, emi_conversion_available, description, pros, cons, best_for, apply_url, is_active, popularity_score, data_source, data_last_verified_at, metadata)
values
  ('hdfc-regalia-gold', 'HDFC Bank', 'HDFC Regalia Gold', 'visa', 'premium', 'gold', null, 2500, 2500, 500000, 2500, 1200000, null, 1200000, 750, 750, 21, 65, null, null, null, '{"travel":{"rate":8,"unit":"points_per_100"},"dining":{"rate":8,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome vouchers worth ₹2,500 on spending ₹15,000 within 90 days","points":2500}'::jsonb, '{"annual_spend":{"spend_threshold":500000,"benefit":"Annual fee waiver + flight vouchers","value":5000}}'::jsonb, 'domestic_and_international', '12 domestic + 6 international per year', null, true, null, null, '15% discount at select partner restaurants', 5000000, null, true, false, 2, null, '4 reward points per INR 150 spent. 1 point = INR 0.50. Accelerated rewards on travel and dining.', array['Complimentary airport lounge access (12/year domestic, 6/year international)', '1% fuel surcharge waiver', 'Milestone benefits: spend INR 5L to get vouchers worth INR 5,000', 'Golf privileges at select courses']::text[], array['High annual fee for the category', 'Reward rate on non-bonus categories is modest', 'Points value drops for non-travel redemption']::text[], array['travel', 'dining', 'shopping']::text[], 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold', true, 90, 'catalog_import', now(), '{}'::jsonb),
  ('sbi-cashback', 'State Bank of India (SBI)', 'SBI Cashback Credit Card', 'visa', 'cashback', 'classic', null, 999, 999, 200000, 999, 300000, null, 300000, 700, 700, 21, 65, null, null, 1, '{"online":{"rate":5,"unit":"percent_cashback"},"offline":{"rate":1,"unit":"percent_cashback"}}'::jsonb, null, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '5% cashback on all online spends. 1% on offline spends.', array['5% cashback on all online transactions', '1% cashback on all other spends', 'Fuel surcharge waiver up to INR 100/month', 'No cashback cap on online spends']::text[], array['No lounge access', 'Cashback capped at ₹5,000/month for offline', 'Annual fee not waived easily']::text[], array['shopping', 'entertainment', 'utilities']::text[], 'https://www.sbicard.com/en/personal/credit-cards/cashback/sbi-card-cashback.page', true, 80, 'catalog_import', now(), '{}'::jsonb),
  ('icici-amazon-pay', 'ICICI Bank', 'ICICI Amazon Pay Credit Card', 'visa', 'cashback', 'classic', null, 0, 0, null, 0, 300000, null, 300000, 700, 700, 21, 65, null, null, 1, '{"amazon":{"rate":5,"unit":"percent_cashback"},"bills_and_dining":{"rate":2,"unit":"percent_cashback"},"other":{"rate":1,"unit":"percent_cashback"}}'::jsonb, '{"description":"₹500 Amazon Pay cashback on first transaction"}'::jsonb, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '5% back on Amazon. 2% on paying bills, dining, fuel. 1% on all other spends.', array['5% cashback on Amazon purchases for Prime members', '2% back on bill payments, dining, and fuel', '1% back on all other spends', 'Lifetime free - no annual fee']::text[], array['Best rewards limited to Amazon ecosystem', 'No lounge access', 'No travel or insurance benefits']::text[], array['shopping', 'dining', 'fuel']::text[], 'https://www.icicibank.com/card/credit-cards/amazon-pay-credit-card', true, 86, 'catalog_import', now(), '{}'::jsonb),
  ('axis-ace', 'Axis Bank', 'Axis Bank ACE Credit Card', 'visa', 'cashback', 'classic', null, 499, 499, 200000, 499, 300000, null, 300000, 700, 700, 21, 65, null, null, 0, '{"google_pay_bills":{"rate":5,"unit":"percent_cashback"},"swiggy_zomato_uber":{"rate":4,"unit":"percent_cashback"},"other":{"rate":2,"unit":"percent_cashback"}}'::jsonb, null, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '5% cashback on bill payments via Google Pay. 4% on Swiggy, Zomato. 2% on everything else.', array['5% cashback on bill payments via Google Pay', '4% cashback on Swiggy, Zomato, Ola, and Uber', '2% cashback on all other spends', 'Fee waiver on spend of INR 2L per year']::text[], array['Google Pay required for maximum cashback', 'No lounge access', 'Annual fee waiver requires ₹2L spend']::text[], array['utilities', 'dining', 'shopping']::text[], 'https://www.axisbank.com/retail/cards/credit-card/ace-credit-card', true, 88, 'catalog_import', now(), '{}'::jsonb),
  ('hdfc-millennia', 'HDFC Bank', 'HDFC Millennia Credit Card', 'mastercard', 'rewards', 'classic', null, 1000, 1000, 100000, 1000, 400000, null, 400000, 720, 720, 21, 65, null, null, 0, '{"amazon_flipkart_myntra":{"rate":5,"unit":"percent_cashback"},"online":{"rate":2.5,"unit":"percent_cashback"},"offline":{"rate":1,"unit":"percent_cashback"}}'::jsonb, '{"description":"₹1,000 cashback on spending ₹1,000 in first 30 days","cashback":1000}'::jsonb, null, 'domestic_only', '4 domestic per year', null, true, null, null, null, null, null, false, false, 3.5, null, '5% cashback on Amazon, Flipkart, Myntra. 2.5% on all online spends. 1% on offline.', array['5% cashback on select e-commerce platforms', '2.5% cashback on all online spends', '1% cashback on offline spends', '4 complimentary domestic lounge visits per year']::text[], array['Cashback capped at ₹1,000/month', 'Lower offline reward rate', 'Annual fee of ₹1,000']::text[], array['shopping', 'entertainment']::text[], 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/millennia-credit-card', true, 82, 'catalog_import', now(), '{}'::jsonb),
  ('sbi-simply-click', 'State Bank of India (SBI)', 'SBI Simply Click Credit Card', 'visa', 'rewards', 'classic', null, 499, 499, 100000, 499, 300000, null, 300000, 700, 700, 21, 65, null, null, 0, '{"partner_merchants":{"rate":10,"unit":"points_per_100"},"online":{"rate":5,"unit":"points_per_100"},"offline":{"rate":1,"unit":"points_per_100"}}'::jsonb, '{"description":"Amazon voucher worth ₹500 on card activation"}'::jsonb, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '10x rewards on partner apps (Amazon, Swiggy, etc.). 5x on all online spends. 1x on others.', array['10x reward points on partner merchants', '5x reward points on all online spends', 'Fee reversal on annual spend of INR 1L', 'Welcome gift of INR 500 Amazon voucher']::text[], array['Reward points not valuable for non-partner redemptions', 'Limited offline rewards', 'No lounge access']::text[], array['shopping', 'dining', 'entertainment']::text[], 'https://www.sbicard.com/en/personal/credit-cards/rewards/simply-click-sbi-card.page', true, 80, 'catalog_import', now(), '{}'::jsonb),
  ('idfc-first-classic', 'IDFC First Bank', 'IDFC FIRST Classic Credit Card', 'visa', 'entry_level', 'classic', null, 0, 0, null, 0, 200000, null, 200000, 700, 700, 21, 65, null, null, 0, '{"all":{"rate":3,"unit":"points_per_100"}}'::jsonb, null, null, 'none', null, null, true, null, null, null, null, null, false, false, 0, null, '3x reward points on all spends. Points never expire. No minimum redemption.', array['Lifetime free - zero annual fee forever', '3x reward points on all spends with no capping', 'Points never expire', 'Zero interest on ATM cash withdrawals for up to 48 days']::text[], array['Lower overall reward rate vs premium cards', 'No lounge access', 'Points value is moderate']::text[], array['shopping', 'groceries', 'utilities']::text[], 'https://www.idfcfirstbank.com/credit-card/classic', true, 84, 'catalog_import', now(), '{}'::jsonb),
  ('idfc-first-wow', 'IDFC First Bank', 'IDFC FIRST WOW! Credit Card', 'visa', 'entry_level', 'classic', null, 0, 0, null, 0, null, null, null, null, null, 18, 65, null, null, 0, '{}'::jsonb, null, null, 'none', null, null, false, null, null, null, null, null, false, false, 3.5, null, 'FD-backed secured credit card with instant issuance and basic reward benefits.', array['FD-backed secured card with credit limit linked to your fixed deposit', 'Suitable for first-time users and users building credit history', 'No income proof required for eligibility', 'Can be useful for users aged 18+ with an FD relationship']::text[], array['Credit limit tied to FD amount', 'Lower reward rate', 'No lounge or premium benefits']::text[], array['shopping', 'travel', 'utilities']::text[], 'https://www.idfcfirstbank.com/credit-card/first-wow', true, 82, 'catalog_import', now(), '{}'::jsonb),
  ('amex-membership-rewards', 'American Express (Amex)', 'American Express Membership Rewards', 'amex', 'rewards', 'classic', null, 4500, 4500, 150000, 4500, 600000, null, 600000, 700, 700, 21, 65, null, null, 0, '{"all":{"rate":1,"unit":"points_per_100"}}'::jsonb, null, '{"monthly_4txn":{"spend_threshold":6000,"benefit":"1,000 bonus MR points on 4 transactions per month","value":1000}}'::jsonb, 'domestic_only', '4 domestic per year via Priority Pass', null, false, null, null, 'Up to 20% discount at select restaurants via Amex Dining Program', null, null, false, false, 3.5, null, '1 MR point per INR 50 spent. 1000 bonus points on 4 transactions monthly. 18-karat gold collection.', array['1000 bonus points on 4+ transactions per month', 'Premium dining benefits with select restaurants', 'Travel and shopping vouchers via Amex rewards catalog', 'Fraud protection guarantee']::text[], array['Limited merchant acceptance in India', 'High annual fee', 'No fuel surcharge waiver']::text[], array['dining', 'travel', 'shopping']::text[], 'https://www.americanexpress.com/in/credit-cards/membership-rewards-credit-card/', true, 80, 'catalog_import', now(), '{}'::jsonb),
  ('kotak-811-dream', 'Kotak Mahindra Bank', 'Kotak 811 #DreamDifferent', 'visa', 'entry_level', 'classic', null, 0, 0, null, 0, null, null, null, null, null, 21, 65, null, null, 0, '{}'::jsonb, null, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '2 reward points per INR 100 spent. Points redeemable for cashback or vouchers.', array['Lifetime free credit card', '2 reward points per INR 100 spent', 'Fuel surcharge waiver', 'Easy EMI conversion for purchases above INR 2,500']::text[], array['Very low reward rate', 'No lounge access', 'Limited benefits overall']::text[], array['fuel', 'groceries', 'utilities']::text[], 'https://www.kotak.com/en/personal-banking/cards/credit-cards/811-dream-different.html', true, 70, 'catalog_import', now(), '{}'::jsonb),
  ('axis-myzone', 'Axis Bank', 'Axis Bank MY Zone Credit Card', 'visa', 'entry_level', 'classic', null, 0, 0, null, 0, 200000, null, 200000, 700, 700, 21, 65, null, null, 0, '{}'::jsonb, null, null, 'none', null, null, true, null, 'Buy 1 Get 1 on movie tickets via Paytm (up to ₹250 discount)', 'Discounts on Swiggy, Zomato orders', null, null, false, false, 3.5, null, '4 EDGE reward points per INR 200 spent. Box office movie offers.', array['Lifetime free card', 'Buy 1 Get 1 free on movie tickets (Paytm)', 'Discounts on Swiggy, Zomato, and other platforms', 'Fuel surcharge waiver']::text[], array['Low overall reward rate', 'No lounge access', 'Movie benefit capped at ₹250/month']::text[], array['entertainment', 'dining']::text[], 'https://www.axisbank.com/retail/cards/credit-card/my-zone-credit-card', true, 76, 'catalog_import', now(), '{}'::jsonb),
  ('hdfc-diners-club-black', 'HDFC Bank', 'HDFC Diners Club Black', 'diners', 'premium', 'infinite', null, 10000, 10000, 500000, 10000, 1800000, null, 1800000, 780, 780, 21, 65, null, null, 0, '{"smartbuy_travel":{"rate":33,"unit":"points_per_100"},"dining":{"rate":10,"unit":"points_per_100"},"other":{"rate":5,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome vouchers worth ₹5,000","points":5000}'::jsonb, '{"spend_8l":{"spend_threshold":800000,"benefit":"Annual memberships (Amazon Prime, Zomato Gold, etc.)","value":10000},"spend_5l":{"spend_threshold":500000,"benefit":"Annual fee waiver + bonus vouchers","value":5000}}'::jsonb, 'domestic_and_international', 'Unlimited domestic and international', null, true, null, 'Complimentary BookMyShow tickets (Buy 1 Get 1)', 'Access to exclusive dining experiences and chef table events', 10000000, 500000, true, true, 1.99, null, '33% reward rate via 10x points on select categories. Points = INR 1 each redeemable for flights and hotels.', array['Unlimited domestic and international airport lounge access', '10x reward points on dining, shopping, travel via SmartBuy', 'Complimentary golf rounds and club memberships', 'Annual memberships (Amazon Prime, Zomato Gold, etc.)']::text[], array['Very high income requirement (₹18L+)', 'Diners Club acceptance is limited in India', 'High annual fee of ₹10,000']::text[], array['travel', 'dining', 'shopping', 'entertainment']::text[], 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/diners-club-black', true, 96, 'catalog_import', now(), '{}'::jsonb),
  ('icici-sapphiro', 'ICICI Bank', 'ICICI Sapphiro Credit Card', 'visa', 'premium', 'signature', null, 3500, 3500, 600000, 3500, 1500000, null, 1500000, 750, 750, 21, 65, null, null, 0, '{"dining_travel":{"rate":8,"unit":"points_per_100"},"other":{"rate":4,"unit":"points_per_100"}}'::jsonb, null, null, 'domestic_and_international', 'Domestic and international lounge access', null, true, null, null, null, 5000000, null, true, false, 2, null, '4 reward points per INR 100 (2x on dining, travel). Points convertible to airmiles.', array['2x reward points on dining and travel', 'Complimentary domestic and international lounge access', 'Golf privileges at select courses', 'Annual fee reversal on spend of INR 6L']::text[], array['High income requirement', 'Annual fee waiver needs ₹6L spend', 'Points value varies by redemption type']::text[], array['travel', 'dining']::text[], 'https://www.icicibank.com/card/credit-cards/icici-bank-sapphiro-credit-card', true, 86, 'catalog_import', now(), '{}'::jsonb),
  ('rbl-shoprite', 'RBL Bank', 'RBL Shoprite Credit Card', 'mastercard', 'cashback', 'classic', null, 0, 0, null, 0, 200000, null, 200000, 650, 650, 21, 65, null, null, 0, '{"grocery":{"rate":5,"unit":"percent_cashback"},"other":{"rate":1.25,"unit":"percent_cashback"}}'::jsonb, null, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '5% cashback on grocery spends. 1.25% on all other retail spends.', array['5% cashback on grocery purchases', '1.25% cashback on all other retail spends', 'Lifetime free card', 'Fuel surcharge waiver']::text[], array['Low non-grocery reward rate', 'No lounge access', 'Limited premium benefits']::text[], array['groceries', 'shopping']::text[], 'https://www.rblbank.com/credit-cards/shoprite-credit-card', true, 74, 'catalog_import', now(), '{}'::jsonb),
  ('indusind-legend', 'IndusInd Bank', 'IndusInd Legend Credit Card', 'visa', 'premium', 'signature', null, 2999, 2999, 300000, 2999, 1000000, null, 1000000, 750, 750, 21, 65, null, null, 0, '{"weekend":{"rate":5,"unit":"points_per_100"},"weekday":{"rate":3,"unit":"points_per_100"}}'::jsonb, null, null, 'domestic_only', 'Priority Pass with 4 visits per year', null, true, null, null, null, 3000000, null, false, true, 2.5, null, '3 reward points per INR 100. Weekend reward boosts (5x). Points redeemable as airmiles.', array['Weekend reward boost up to 5x points', 'Complimentary Priority Pass lounge access', 'Concierge services', 'Annual fee waiver on INR 3L spend']::text[], array['Weekend-dependent bonus rewards', 'Priority Pass visits are limited', 'Annual fee of ₹2,999']::text[], array['travel', 'entertainment', 'dining']::text[], 'https://www.indusind.com/in/en/personal/cards/credit-card/legend-credit-card.html', true, 80, 'catalog_import', now(), '{}'::jsonb),
  ('au-lit', 'AU Small Finance Bank', 'AU LIT Credit Card', 'mastercard', 'rewards', 'classic', null, 1999, 1999, 250000, 1999, 400000, null, 400000, 700, 700, 21, 65, null, null, 0, '{"movies_ott_gaming":{"rate":5,"unit":"percent_cashback"},"dining_delivery":{"rate":2,"unit":"percent_cashback"},"other":{"rate":1,"unit":"percent_cashback"}}'::jsonb, null, null, 'domestic_only', '2 domestic lounge visits per quarter', null, true, null, 'Buy 1 Get 1 on movie tickets every month', null, null, null, false, false, 3.5, null, '5% cashback on movies, OTT, and gaming. 2% on dining, food delivery. 1% on all.', array['5% cashback on movies, OTT, and gaming', '2% on dining and food delivery', 'Buy 1 Get 1 on movie tickets monthly', 'Annual fee waiver on INR 2.5L spend']::text[], array['Limited lounge visits', 'Annual fee of ₹1,999', 'Cashback caps on dining category']::text[], array['entertainment', 'dining']::text[], 'https://www.aubank.in/credit-card/lit-credit-card', true, 82, 'catalog_import', now(), '{}'::jsonb),
  ('hdfc-indian-oil', 'HDFC Bank', 'HDFC Indian Oil Credit Card', 'visa', 'fuel', 'classic', null, 0, 500, 50000, 500, 300000, null, 300000, 700, 700, 21, 65, null, null, 0, '{"indian_oil":{"rate":5,"unit":"percent_cashback"},"fuel_all":{"rate":1,"unit":"percent_surcharge_waiver"}}'::jsonb, '{"description":"2,100 fuel points on card activation","points":2100}'::jsonb, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '50 fuel points per INR 150 spent at Indian Oil. 5% savings on fuel.', array['5% value back as fuel points at Indian Oil outlets', '1% fuel surcharge waiver across all fuel stations', 'Annual fee waiver on INR 50,000 spend', 'Welcome benefit of 2,100 fuel points']::text[], array['Benefits mostly limited to Indian Oil outlets', 'No lounge access', 'Low non-fuel rewards']::text[], array['fuel']::text[], 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/indianoil-credit-card', true, 78, 'catalog_import', now(), '{}'::jsonb),
  ('icici-coral', 'ICICI Bank', 'ICICI Coral Credit Card', 'visa', 'rewards', 'classic', null, 500, 500, 150000, 500, 350000, null, 350000, 700, 700, 21, 65, null, null, 0, '{"all":{"rate":2,"unit":"points_per_100"}}'::jsonb, null, null, 'domestic_only', '1 domestic lounge visit per quarter', null, true, null, 'Buy 1 Get 1 on BookMyShow (up to 4 times per month)', '15% discount at select partner restaurants', null, null, false, false, 3.5, null, '2 PAYBACK points per INR 100 spent. Buy 1 Get 1 on movie tickets.', array['Buy 1 Get 1 on BookMyShow (up to 4x/month)', '2 PAYBACK points per INR 100 spent', 'Dining discounts at partner restaurants', 'Fuel surcharge waiver']::text[], array['Low base reward rate', 'Limited lounge visits (1/quarter)', 'Annual fee of ₹500']::text[], array['entertainment', 'dining', 'shopping']::text[], 'https://www.icicibank.com/card/credit-cards/icici-bank-coral-credit-card', true, 76, 'catalog_import', now(), '{}'::jsonb),
  ('yes-first-preferred', 'Yes Bank', 'YES FIRST Preferred Credit Card', 'mastercard', 'rewards', 'classic', null, 999, 999, 250000, 999, 500000, null, 500000, 700, 700, 21, 65, null, null, 0, '{"travel_dining":{"rate":6,"unit":"points_per_100"},"other":{"rate":3,"unit":"points_per_100"}}'::jsonb, null, null, 'domestic_only', '4 domestic per year', null, true, null, 'BookMyShow offers on select days', null, null, null, false, false, 3.5, null, '3 reward points per INR 100. 6x on travel and dining. Points convertible to airmiles.', array['6x reward points on travel and dining', 'Complimentary domestic lounge access quarterly', 'Movie ticket offers on BookMyShow', 'Annual fee waiver on INR 2.5L spend']::text[], array['Yes Bank acceptance concerns in past', 'Limited international lounge access', 'Annual fee waiver needs ₹2.5L spend']::text[], array['travel', 'dining', 'entertainment']::text[], 'https://www.yesbank.in/personal-banking/yes-first/credit-cards/yes-first-preferred', true, 74, 'catalog_import', now(), '{}'::jsonb),
  ('sbi-bpcl', 'State Bank of India (SBI)', 'SBI BPCL Credit Card', 'visa', 'fuel', 'classic', null, 499, 499, 100000, 499, 300000, null, 300000, 700, 700, 21, 65, null, null, 0, '{"bpcl_fuel":{"rate":13,"unit":"points_per_100"},"dining_movies":{"rate":5,"unit":"points_per_100"},"other":{"rate":1,"unit":"points_per_100"}}'::jsonb, null, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '13x reward points on BPCL fuel spends. 5x on dining and movies. 1x on other spends.', array['13x reward points at BPCL fuel stations', '5x rewards on dining and movies', 'Fuel surcharge waiver at all fuel stations', 'Annual fee reversal on INR 1L spend']::text[], array['Best rewards limited to BPCL stations', 'No lounge access', 'Moderate income requirements']::text[], array['fuel', 'dining', 'entertainment']::text[], 'https://www.sbicard.com/en/personal/credit-cards/travel-fuel/bpcl-sbi-card.page', true, 80, 'catalog_import', now(), '{}'::jsonb),
  ('hdfc-infinia', 'HDFC Bank', 'HDFC Infinia Credit Card', 'visa', 'super_premium', 'infinite', null, 12500, 12500, 1000000, 12500, 3000000, null, 3000000, 800, 800, 21, 65, null, null, 3.33, '{"smartbuy_travel":{"rate":33,"unit":"points_per_100"},"dining":{"rate":10,"unit":"points_per_100"},"other":{"rate":5,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome voucher worth ₹10,000 on first transaction","points":10000}'::jsonb, '{"annual_10l":{"spend_threshold":1000000,"benefit":"Annual fee waiver + Club Marriott membership","value":15000},"annual_8l":{"spend_threshold":800000,"benefit":"Bonus reward points worth ₹7,500","value":7500}}'::jsonb, 'domestic_and_international', 'Unlimited domestic and international', null, true, null, null, 'Access to the fine dining program with complimentary meals at 5-star restaurants', 20000000, 1000000, true, true, 2, null, '5 reward points per INR 150. 10x on SmartBuy. 1 point = INR 1 for travel.', array['Unlimited domestic and international lounge access for primary and add-on cardholders', 'Complimentary Club Marriott membership', '10x rewards on travel, hotel, and dining via SmartBuy', 'Concierge services and golf privileges']::text[], array['By-invitation-only for most applicants', 'Very high income requirement (₹30L+)', 'High annual fee of ₹12,500']::text[], array['travel', 'dining', 'shopping']::text[], 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/hdfc-bank-infinia-credit-card', true, 98, 'catalog_import', now(), '{}'::jsonb),
  ('axis-reserve', 'Axis Bank', 'Axis Bank Reserve Credit Card', 'visa', 'super_premium', 'infinite', null, 50000, 50000, null, 50000, 6000000, null, 6000000, 800, 800, 21, 65, null, null, 0, '{"travel_portals":{"rate":15,"unit":"points_per_100"},"dining_intl":{"rate":10,"unit":"points_per_100"},"other":{"rate":5,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome gift pack valued at ₹25,000 on first spend","points":25000}'::jsonb, '{"annual_35l":{"spend_threshold":3500000,"benefit":"Annual fee reversal + exclusive luxury experiences","value":50000}}'::jsonb, 'domestic_only', 'Unlimited worldwide via Priority Pass', null, true, null, null, 'Exclusive curated dining experiences at Michelin-starred and premium restaurants', 30000000, 2000000, true, true, 0, null, '15 EDGE reward points per INR 200. 10x on travel portals. Points redeemable for flights/hotels.', array['Unlimited Priority Pass lounge access worldwide', 'Complimentary golf at select courses globally', 'Concierge services 24/7', 'Annual memberships (Club Marriott, Amazon Prime)']::text[], array['Extremely high annual fee of ₹50,000', 'Income requirement of ₹60L+', 'Overkill for moderate spenders']::text[], array['travel', 'dining', 'shopping']::text[], 'https://www.axisbank.com/retail/cards/credit-card/reserve', true, 94, 'catalog_import', now(), '{}'::jsonb),
  ('sbi-elite', 'State Bank of India (SBI)', 'SBI Elite Credit Card', 'mastercard', 'premium', 'platinum', null, 4999, 4999, 1000000, 4999, 1200000, null, 1200000, 750, 750, 21, 65, null, null, 0, '{"dining_intl":{"rate":10,"unit":"points_per_100"},"movies":{"rate":10,"unit":"points_per_100"},"other":{"rate":2,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome gift of ₹5,000 as e-vouchers on first spend of ₹5,000","points":5000}'::jsonb, null, 'domestic_and_international', '6 domestic + 2 international per year', null, true, null, null, null, 10000000, null, true, false, 1.99, null, '10x reward points on dining, movies, and international spends. 2x on all others.', array['6 complimentary domestic lounge visits per year', '2 complimentary international lounge visits per year', '10x reward points on dining, movies, and international spends', 'Travel milestone benefit; verify the current partner with the issuer']::text[], array['High annual fee of ₹4,999', 'Limited international lounge visits (only 2)', 'Fee waiver needs ₹10L annual spend']::text[], array['travel', 'dining', 'entertainment']::text[], 'https://www.sbicard.com/en/personal/credit-cards/travel-fuel/sbi-card-elite.page', true, 88, 'catalog_import', now(), '{}'::jsonb),
  ('icici-emeralde', 'ICICI Bank', 'ICICI Emeralde Credit Card', 'mastercard', 'super_premium', 'world', null, 12000, 12000, 1500000, 12000, 2400000, null, 2400000, 780, 780, 21, 65, null, null, 0, '{"international":{"rate":12,"unit":"points_per_100"},"domestic_travel":{"rate":6,"unit":"points_per_100"},"other":{"rate":6,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome Kit with premium memberships worth ₹12,000","points":12000}'::jsonb, null, 'domestic_and_international', 'Unlimited domestic and international', null, true, null, null, 'Zomato Pro Plus and exclusive chef-curated dining events', 15000000, 700000, true, true, 1.5, null, '6 reward points per INR 100. 2x on international spends. Points convertible to airmiles.', array['Unlimited domestic and international lounge access for primary and add-on cardholders', 'Complimentary golf rounds at 30+ Indian golf courses', 'Concierge services and exclusive dining benefits', 'Complimentary Times Prime membership']::text[], array['Very high income requirement (₹24L+)', 'Annual fee of ₹12,000', 'Not easily available without ICICI relationship']::text[], array['travel', 'dining', 'shopping']::text[], 'https://www.icicibank.com/card/credit-cards/icici-bank-emeralde-credit-card', true, 92, 'catalog_import', now(), '{}'::jsonb),
  ('axis-atlas', 'Axis Bank', 'Axis Bank Atlas Credit Card', 'mastercard', 'travel', 'world', null, 5000, 5000, 750000, 5000, 1500000, null, 1500000, 750, 750, 21, 65, null, null, 0, '{"travel":{"rate":12,"unit":"points_per_100"},"dining":{"rate":6,"unit":"points_per_100"},"other":{"rate":5,"unit":"points_per_100"}}'::jsonb, '{"description":"5,000 EDGE Miles on first spend within 30 days","points":5000}'::jsonb, null, 'domestic_and_international', '4 domestic + 2 international per quarter', null, true, null, null, null, 5000000, null, false, false, 0, null, '12 EDGE Miles per INR 200 on travel portals. 5 miles per INR 200 on other spends.', array['12 EDGE Miles on travel bookings', '4 domestic lounge visits per quarter', '2 international lounge visits per quarter', 'Miles transferable to 10+ airline and hotel programs']::text[], array['Annual fee of ₹5,000', 'Miles transferability limited to select programs', 'Best value only through travel bookings']::text[], array['travel', 'dining']::text[], 'https://www.axisbank.com/retail/cards/credit-card/atlas-credit-card', true, 90, 'catalog_import', now(), '{}'::jsonb),
  ('hdfc-tata-neu-plus', 'HDFC Bank', 'Tata Neu Plus HDFC Bank Credit Card', 'rupay', 'rewards', 'classic', null, 499, 499, 100000, 499, 300000, null, 300000, 700, 700, 21, 65, null, null, 0, '{"tata_brands":{"rate":5,"unit":"percent_cashback"},"other":{"rate":1.5,"unit":"percent_cashback"}}'::jsonb, '{"description":"NeuCoins worth ₹500 on first spend of ₹500","cashback":500}'::jsonb, null, 'domestic_only', '4 domestic per year', null, true, null, null, null, null, null, false, false, 3.5, null, '5% NeuCoins on eligible Tata brands. 1.5% on other eligible spends.', array['5% NeuCoins on all Tata brand purchases', '1.5% NeuCoins on all other spends', 'Annual fee waiver on INR 1L spend', 'Welcome NeuCoins worth INR 500']::text[], array['Best rewards limited to Tata ecosystem', 'RuPay network has limited international acceptance', 'Moderate base reward rate']::text[], array['shopping', 'groceries', 'entertainment']::text[], 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/tata-neu-plus-hdfc-bank-credit-card', true, 80, 'catalog_import', now(), '{}'::jsonb),
  ('hdfc-tata-neu-infinity', 'HDFC Bank', 'Tata Neu Infinity HDFC Bank Credit Card', 'rupay', 'premium', 'platinum', null, 1499, 1499, 300000, 1499, 600000, null, 600000, 730, 730, 21, 65, null, null, 1.5, '{"tata_brands":{"rate":10,"unit":"percent_cashback"},"emi_spends":{"rate":5,"unit":"percent_cashback"},"other":{"rate":1.5,"unit":"percent_cashback"}}'::jsonb, '{"description":"NeuCoins worth ₹1,500 on first spend of ₹3,000","cashback":1500}'::jsonb, null, 'domestic_only', '8 domestic per year', null, true, null, null, null, null, null, false, false, 3.5, null, '10% NeuCoins on Tata brands. 5% on EMI transactions. 1.5% on all other spends.', array['10% NeuCoins on Tata brands ecosystem', '5% on EMI spends and select categories', '8 complimentary airport lounge visits per year', 'Annual fee waiver on INR 3L spend']::text[], array['RuPay network limits international usage', 'Annual fee of ₹1,499', 'Premium benefits lag behind Visa/MC cards at same price']::text[], array['shopping', 'travel', 'entertainment']::text[], 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/tata-neu-infinity-hdfc-bank-credit-card', true, 84, 'catalog_import', now(), '{}'::jsonb),
  ('icici-instant-platinum', 'ICICI Bank', 'ICICI Instant Platinum Credit Card', 'mastercard', 'secured', 'platinum', null, 0, 500, null, 500, null, null, null, null, null, 21, 65, null, null, 0, '{}'::jsonb, null, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '2 PAYBACK points per INR 100 spent. FD-backed secured card.', array['FD-backed secured card – no income proof required', '2 PAYBACK points per INR 100 spent', '1% fuel surcharge waiver', 'EMI conversion on purchases above INR 2,500']::text[], array['Credit limit tied to FD value', 'Low reward rate', 'No lounge access or premium benefits']::text[], array['shopping', 'utilities', 'groceries']::text[], 'https://www.icicibank.com/card/credit-cards/icici-bank-instant-platinum-card', true, 72, 'catalog_import', now(), '{}'::jsonb),
  ('sbi-prime', 'State Bank of India (SBI)', 'SBI Prime Credit Card', 'mastercard', 'premium', 'platinum', null, 2999, 2999, 300000, 2999, 900000, null, 900000, 750, 750, 21, 65, null, null, 0, '{"dining_grocery":{"rate":10,"unit":"points_per_100"},"movies":{"rate":10,"unit":"points_per_100"},"other":{"rate":2,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome vouchers worth ₹3,000 on spending ₹5,000 in 60 days","points":3000}'::jsonb, '{"spend_3l":{"spend_threshold":300000,"benefit":"Annual fee reversal","value":2999}}'::jsonb, 'domestic_only', '8 domestic per year', null, true, null, null, 'Complimentary access to Zomato dining program with 20% off at select restaurants', 5000000, null, false, false, 2.5, null, '10 reward points per INR 100 on dining, groceries, and movies. 2x on other spends.', array['10x reward points on dining, groceries, and departmental stores', 'Travel membership benefit; verify the current partner with the issuer', 'Complimentary domestic lounge access (8 per year)', 'Annual fee reversal on INR 3L spend']::text[], array['Annual fee of INR 2,999', 'International lounge access not included', 'Travel partner benefits may change']::text[], array['dining', 'shopping', 'travel']::text[], 'https://www.sbicard.com/en/personal/credit-cards/rewards/sbi-card-prime.page', true, 86, 'catalog_import', now(), '{}'::jsonb),
  ('kotak-white', 'Kotak Mahindra Bank', 'Kotak White Credit Card', 'visa', 'premium', 'signature', null, 3000, 3000, 400000, 3000, 800000, null, 800000, 750, 750, 21, 65, null, null, 0, '{"travel_dining_entertainment":{"rate":8,"unit":"points_per_100"},"other":{"rate":4,"unit":"points_per_100"}}'::jsonb, null, null, 'domestic_only', '12 domestic per year', null, true, null, null, null, 5000000, null, false, false, 2.5, null, '8 Kotak reward points per INR 200 spent. 4x on travel, dining, entertainment.', array['4x reward points on travel, dining, and entertainment', 'Complimentary domestic lounge visits (12 per year)', '1% fuel surcharge waiver', 'Annual fee reversal on INR 4L spend']::text[], array['Annual fee of ₹3,000', 'Limited international lounge access', 'Reward points value is moderate']::text[], array['travel', 'dining', 'entertainment']::text[], 'https://www.kotak.com/en/personal-banking/cards/credit-cards/white-reserve.html', true, 82, 'catalog_import', now(), '{}'::jsonb),
  ('kotak-royale', 'Kotak Mahindra Bank', 'Kotak Royale Signature Credit Card', 'visa', 'rewards', 'signature', null, 1499, 1499, 200000, 1499, 500000, null, 500000, 720, 720, 21, 65, null, null, 0, '{"dining_travel_intl":{"rate":8,"unit":"points_per_100"},"other":{"rate":4,"unit":"points_per_100"}}'::jsonb, null, null, 'domestic_only', '2 domestic per quarter', null, true, null, null, null, null, null, false, false, 3.5, null, '4 Kotak reward points per INR 150. 2x on dining, travel, and international spends.', array['2x reward points on dining, travel, and international spends', '2 complimentary domestic lounge visits per quarter', '1% fuel surcharge waiver', 'Annual fee reversal on INR 2L spend']::text[], array['Annual fee of ₹1,499', 'Limited domestic lounge visits', 'No international lounge access']::text[], array['travel', 'dining', 'shopping']::text[], 'https://www.kotak.com/en/personal-banking/cards/credit-cards/royale-signature.html', true, 78, 'catalog_import', now(), '{}'::jsonb),
  ('axis-flipkart', 'Axis Bank', 'Flipkart Axis Bank Credit Card', 'visa', 'cashback', 'classic', null, 500, 500, 200000, 500, 300000, null, 300000, 700, 700, 21, 65, null, null, 1.5, '{"flipkart_cleartrip":{"rate":5,"unit":"percent_cashback"},"preferred_merchants":{"rate":4,"unit":"percent_cashback"},"other":{"rate":1.5,"unit":"percent_cashback"}}'::jsonb, '{"description":"Flipkart voucher worth ₹500 on approval","cashback":500}'::jsonb, null, 'domestic_only', '4 domestic per year', null, true, null, null, null, null, null, false, false, 3.5, null, '5% cashback on Flipkart, Cleartrip, 2GUD. 4% on preferred merchants. 1.5% unlimited cashback.', array['5% cashback on Flipkart and partner platforms', '4% cashback on preferred merchants (Swiggy, Uber, PVR)', '1.5% unlimited cashback on all other spends', 'Annual fee waiver on INR 2L spend']::text[], array['Best rewards limited to Flipkart ecosystem', 'Annual fee of ₹500', 'Cashback is credited as statement credit']::text[], array['shopping', 'dining', 'entertainment']::text[], 'https://www.axisbank.com/retail/cards/credit-card/flipkart-axis-bank-credit-card', true, 84, 'catalog_import', now(), '{}'::jsonb),
  ('hdfc-biz-moneyback', 'HDFC Bank', 'HDFC MoneyBack+ Credit Card', 'mastercard', 'cashback', 'classic', null, 500, 500, 50000, 500, 200000, null, 200000, 700, 700, 21, 65, null, null, 0, '{"amazon_bigbasket_flipkart":{"rate":5,"unit":"points_per_100"},"other":{"rate":2,"unit":"points_per_100"}}'::jsonb, '{"description":"₹500 CashPoints on first spend of ₹500","cashback":500}'::jsonb, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '5% cashback on Amazon, BigBasket, Flipkart, Swiggy. 2x on all other spends.', array['5x cashpoints on online spends (Amazon, BigBasket, Flipkart, Swiggy)', '2x cashpoints on all other spends', 'Welcome benefit of INR 500 CashPoints', 'Annual fee reversal on INR 50K spend']::text[], array['CashPoints expire in 2 years', 'No lounge access', 'Low fee waiver threshold but low rewards too']::text[], array['shopping', 'groceries', 'dining']::text[], 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/moneyback-credit-card', true, 78, 'catalog_import', now(), '{}'::jsonb),
  ('amex-plat-travel', 'American Express (Amex)', 'American Express Platinum Travel Card', 'amex', 'travel', 'platinum', null, 3500, 5000, null, 5000, 600000, null, 600000, 720, 720, 21, 65, null, null, 0, '{"all":{"rate":4,"unit":"points_per_100"},"airline_partners":{"rate":8,"unit":"points_per_100"}}'::jsonb, '{"description":"Taj voucher or Marriott e-gift card worth ₹4,000 on first spend","points":4000}'::jsonb, null, 'domestic_only', '8 domestic per year', null, false, null, null, null, 30000000, null, false, false, 3.5, null, '1 Membership Rewards point per INR 50. Airline partner offers can change.', array['Airline partner benefits; verify current partners before applying', '8 domestic airport lounge visits per year', 'Travel insurance cover up to INR 3 crore', 'Annual fee reduced to INR 3,500 on renewal']::text[], array['Limited merchant acceptance for Amex in India', 'No fuel surcharge waiver', 'Annual fee of ₹5,000 not easily waived']::text[], array['travel', 'dining']::text[], 'https://www.americanexpress.com/in/credit-cards/platinum-travel-credit-card/', true, 84, 'catalog_import', now(), '{}'::jsonb),
  ('amex-gold-charge', 'American Express (Amex)', 'American Express Gold Card', 'amex', 'premium', 'gold', null, 1000, 4500, 600000, 4500, 600000, null, 600000, 720, 720, 21, 65, null, null, 0, '{"all":{"rate":5,"unit":"points_per_100"}}'::jsonb, null, '{"monthly_bonus":{"spend_threshold":6000,"benefit":"1,000 bonus MR points on 4 transactions of ₹1,500+ per month","value":1000}}'::jsonb, 'domestic_only', '4 domestic per year via Priority Pass', null, false, null, null, 'Premium dining privileges at selected 5-star restaurants through Amex Dining Program', null, null, false, false, 3.5, null, '1000 bonus MR points on spending INR 1,500 four times in a month.', array['1000 monthly bonus points on 4 transactions of INR 1,500+', 'Dining privileges at premium restaurants', 'Points never expire', 'Fee waiver if you spend INR 6L or more in a year']::text[], array['Limited merchant acceptance in India', 'No fuel surcharge waiver', 'Points never expire but Amex acceptance is limited']::text[], array['dining', 'travel', 'shopping']::text[], 'https://www.americanexpress.com/in/credit-cards/gold-card/', true, 78, 'catalog_import', now(), '{}'::jsonb),
  ('indusind-pinnacle', 'IndusInd Bank', 'IndusInd Pinnacle Credit Card', 'visa', 'super_premium', 'infinite', null, 50000, 50000, null, 50000, 5000000, null, 5000000, 800, 800, 21, 65, null, null, 0, '{"all":{"rate":20,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome kit valued at ₹50,000 with luxury brand vouchers","points":50000}'::jsonb, '{"annual_50l":{"spend_threshold":5000000,"benefit":"Private jet charter credits + luxury hotel stays","value":100000}}'::jsonb, 'domestic_only', 'Unlimited worldwide via Priority Pass', null, true, null, null, 'Bespoke dining at Michelin-starred restaurants and private chef arrangements', 50000000, 2500000, true, true, 0, null, '20 reward points per INR 100. Unlimited redemption for travel, merchandise, and experiences.', array['Unlimited Priority Pass international lounge access', 'Personal concierge and lifestyle manager', 'Golf privileges at over 50 courses globally', 'Private jet charter assistance']::text[], array['Extremely high annual fee of ₹50,000', 'Income requirement of ₹50L+', 'Overkill for most consumers']::text[], array['travel', 'dining', 'shopping']::text[], 'https://www.indusind.com/in/en/personal/cards/credit-card/pinnacle-credit-card.html', true, 92, 'catalog_import', now(), '{}'::jsonb),
  ('rbl-world-safari', 'RBL Bank', 'RBL World Safari Credit Card', 'mastercard', 'travel', 'world', null, 3000, 3000, 300000, 3000, 700000, null, 700000, 730, 730, 21, 65, null, null, 0, '{"travel":{"rate":6,"unit":"points_per_100"},"other":{"rate":2,"unit":"points_per_100"}}'::jsonb, null, null, 'domestic_and_international', '4 domestic + 1 international per quarter', null, true, null, null, null, 5000000, null, false, false, 2, null, '6 travel points per INR 100 on travel portals. 2 points on all other spends.', array['6 travel points per INR 100 on travel spends', '4 complimentary domestic lounge visits per quarter', '1 international lounge visit per quarter', 'Travel insurance cover']::text[], array['Annual fee of ₹3,000', 'RBL has smaller branch network', 'Non-travel rewards are low']::text[], array['travel', 'dining']::text[], 'https://www.rblbank.com/credit-cards/world-safari', true, 80, 'catalog_import', now(), '{}'::jsonb),
  ('idfc-first-wealth', 'IDFC First Bank', 'IDFC FIRST Wealth Credit Card', 'visa', 'premium', 'signature', null, 0, 0, null, 0, 1500000, null, 1500000, 750, 750, 21, 65, null, null, 0, '{"travel":{"rate":10,"unit":"points_per_100"},"dining_online":{"rate":5,"unit":"points_per_100"},"other":{"rate":3,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome kit with premium memberships and vouchers","points":5000}'::jsonb, null, 'domestic_and_international', 'Unlimited domestic + 4 international per year', null, true, null, null, null, 10000000, null, false, true, 0, null, '10x rewards on travel. 5x on dining and online spends. 3x on all others. Points never expire.', array['Lifetime free – zero annual fee', '10x reward points on travel portals', '5x on dining and online spends', 'Unlimited complimentary domestic lounge access']::text[], array['Requires IDFC FIRST relationship with high balance', 'Must maintain NRV for lifetime free status', 'Not available to all applicants']::text[], array['travel', 'dining', 'shopping']::text[], 'https://www.idfcfirstbank.com/credit-card/wealth', true, 92, 'catalog_import', now(), '{}'::jsonb),
  ('federalbank-celesta', 'Federal Bank', 'Federal Bank Celesta Credit Card', 'mastercard', 'premium', 'world', null, 7500, 7500, 500000, 7500, 1000000, null, 1000000, 750, 750, 21, 65, null, null, 0, '{"dining_travel":{"rate":10,"unit":"points_per_100"},"other":{"rate":5,"unit":"points_per_100"}}'::jsonb, null, null, 'domestic_only', '8 per year via Priority Pass', null, true, null, null, null, 10000000, null, true, false, 2, null, '5 reward points per INR 100 on all categories. 2x on dining and travel.', array['Complimentary Priority Pass lounge access (8 visits per year)', '2x rewards on dining and travel', 'Golf privileges at select courses', 'Welcome vouchers worth INR 5,000']::text[], array['High annual fee of ₹7,500', 'Federal Bank has limited branch network', 'Less brand recognition than top-tier cards']::text[], array['travel', 'dining', 'shopping']::text[], 'https://www.federalbank.co.in/credit-cards', true, 78, 'catalog_import', now(), '{}'::jsonb),
  ('yes-marquee', 'Yes Bank', 'YES Marquee Credit Card', 'mastercard', 'premium', 'world', null, 9999, 9999, 1000000, 9999, 2000000, null, 2000000, 780, 780, 21, 65, null, null, 0, '{"travel_dining":{"rate":24,"unit":"points_per_100"},"other":{"rate":12,"unit":"points_per_100"}}'::jsonb, '{"description":"Annual membership benefits package worth ₹15,000","points":15000}'::jsonb, null, 'domestic_and_international', 'Unlimited domestic and international', null, true, null, null, null, 15000000, null, true, true, 1.75, null, '24x reward points on travel and dining. 12x on other categories.', array['Unlimited domestic and international lounge access', 'Golf access at 50+ courses in India and abroad', '24x reward points on travel and dining', 'Premium concierge services']::text[], array['Very high annual fee of ₹9,999', 'Yes Bank had stability concerns', 'Fee waiver needs ₹10L spend']::text[], array['travel', 'dining', 'entertainment']::text[], 'https://www.yesbank.in/personal-banking/yes-bank-credit-cards/marquee', true, 86, 'catalog_import', now(), '{}'::jsonb),
  ('au-altura', 'AU Small Finance Bank', 'AU Bank Altura Credit Card', 'mastercard', 'entry_level', 'classic', null, 0, 0, null, 0, 150000, null, 150000, 650, 650, 18, 65, null, null, 1, '{}'::jsonb, null, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '2% cashback on utility bill payments and fuel. 1% on all other spends.', array['Lifetime free card', '2% cashback on utility bills and fuel', '1% cashback on all other spends', 'Fuel surcharge waiver']::text[], array['Low overall reward rate', 'AU Small Finance has limited ATM/branch network', 'No lounge access', 'Limited premium features']::text[], array['utilities', 'fuel', 'shopping']::text[], 'https://www.aubank.in/credit-card/altura', true, 72, 'catalog_import', now(), '{}'::jsonb),
  ('au-zenith', 'AU Small Finance Bank', 'AU Bank Zenith Credit Card', 'mastercard', 'premium', 'signature', null, 7999, 7999, 800000, 7999, 1800000, null, 1800000, 750, 750, 21, 65, null, null, 0, '{"dining_travel_intl":{"rate":20,"unit":"points_per_100"},"other":{"rate":5,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome vouchers worth ₹10,000 on first spend of ₹10,000","points":10000}'::jsonb, null, 'domestic_and_international', 'Unlimited domestic + 8 international per year', null, true, null, null, null, 30000000, null, false, true, 1.5, null, '20 reward points per INR 100 on dining, travel, and international spends. 5x on others.', array['Unlimited domestic lounge access', '8 international lounge visits per year', 'Travel insurance cover up to INR 3 crore', '20x reward points on dining, travel, international spends']::text[], array['High annual fee of ₹7,999', 'AU Small Finance has limited network', 'Fee waiver requires ₹8L spend']::text[], array['travel', 'dining', 'shopping']::text[], 'https://www.aubank.in/credit-card/zenith', true, 88, 'catalog_import', now(), '{}'::jsonb),
  ('hdfc-rupay-biz', 'HDFC Bank', 'HDFC Business MoneyBack Credit Card', 'rupay', 'business', 'classic', null, 500, 500, null, 500, 300000, null, 300000, 700, 700, 21, 65, null, null, 0, '{"telecom_supplies":{"rate":5,"unit":"percent_cashback"},"other":{"rate":2,"unit":"percent_cashback"}}'::jsonb, null, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '5% cashback on business spends, office supplies, and telecom.', array['5% cashback on telecom and business supplies', '2% cashback on all other business spends', 'Fuel surcharge waiver', 'Expense management reports']::text[], array['RuPay has no international acceptance', 'Low base reward rate', 'No lounge access', 'Limited to business-category benefits']::text[], array['utilities', 'shopping', 'fuel']::text[], 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/business-moneyback', true, 74, 'catalog_import', now(), '{}'::jsonb),
  ('sbi-cashback-plus', 'State Bank of India (SBI)', 'SBI SimplySave Credit Card', 'visa', 'cashback', 'classic', null, 499, 499, 100000, 499, 200000, null, 200000, 700, 700, 21, 65, null, null, 0, '{"dining_grocery_movies":{"rate":10,"unit":"points_per_100"},"other":{"rate":1,"unit":"points_per_100"}}'::jsonb, '{"description":"Bonus 2,000 activation points on first ₹2,000 spend","points":2000}'::jsonb, null, 'none', null, null, true, null, null, null, null, null, false, false, 3.5, null, '10x reward points on dining, groceries, movies, and departmental stores. 1x on others.', array['10x reward points on dining, groceries, movies', 'Bonus 2,000 activation points on first INR 2,000 spend', 'Annual fee waiver on INR 1L spend', 'Fuel surcharge waiver']::text[], array['Low non-category reward rate', 'No lounge access', 'Annual fee of ₹499']::text[], array['groceries', 'dining', 'entertainment']::text[], 'https://www.sbicard.com/en/personal/credit-cards/rewards/simplysave-sbi-card.page', true, 78, 'catalog_import', now(), '{}'::jsonb),
  ('icici-rubyx', 'ICICI Bank', 'ICICI Rubyx Credit Card', 'mastercard', 'premium', 'signature', null, 3000, 3000, 500000, 3000, 700000, null, 700000, 740, 740, 21, 65, null, null, 0, '{"weekday_dining":{"rate":5,"unit":"points_per_100"},"other":{"rate":3,"unit":"points_per_100"}}'::jsonb, '{"description":"Vouchers worth ₹5,000 on spending ₹50,000 in 60 days","points":5000}'::jsonb, null, 'domestic_and_international', '1 domestic + 1 international per quarter', null, true, null, 'Buy 1 Get 1 on BookMyShow every month', '5x rewards on weekday dining across all restaurants', 3000000, null, false, false, 2.5, null, '5 reward points per INR 100 on weekday dining. 3 points on all other spends.', array['5x reward points on weekday dining', 'Buy 1 Get 1 on BookMyShow every month', '1 domestic + 1 international lounge visit per quarter', 'Welcome vouchers worth INR 5,000']::text[], array['Annual fee of ₹3,000', 'Dining rewards only on weekdays', 'Fee waiver needs ₹5L spend']::text[], array['dining', 'entertainment', 'shopping']::text[], 'https://www.icicibank.com/card/credit-cards/ruby', true, 80, 'catalog_import', now(), '{}'::jsonb),
  ('axis-magnus', 'Axis Bank', 'Axis Bank Magnus Credit Card', 'mastercard', 'premium', 'signature', null, 12500, 12500, 1500000, 12500, 2000000, null, 2000000, 780, 780, 21, 65, null, null, 0, '{"travel_portals":{"rate":25,"unit":"points_per_100"},"other":{"rate":12,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome benefit of 12,500 EDGE Miles on first spend","points":12500}'::jsonb, '{"annual_15l":{"spend_threshold":1500000,"benefit":"Annual fee reversal + bonus 25,000 miles","value":25000}}'::jsonb, 'domestic_and_international', 'Unlimited domestic + 12 international per year', null, true, null, null, null, 10000000, null, true, true, 0, null, '25 EDGE reward points per INR 200 on travel portals. 12 points on all other spends.', array['Unlimited domestic lounge access', '12 international lounge visits per year via Priority Pass', '25 EDGE Miles on travel portals per INR 200', 'Complimentary golf at select courses']::text[], array['Very high annual fee of ₹12,500', 'Income requirement of ₹20L+', 'Max value is unlocked only via transfer partners']::text[], array['travel', 'dining', 'shopping']::text[], 'https://www.axisbank.com/retail/cards/credit-card/axis-bank-magnus-credit-card', true, 92, 'catalog_import', now(), '{}'::jsonb),
  ('hdfc-swiggy', 'HDFC Bank', 'Swiggy HDFC Bank Credit Card', 'visa', 'cashback', 'classic', null, 500, 500, 200000, 500, 300000, null, 300000, 700, 700, 21, 65, null, null, 1, '{"swiggy":{"rate":10,"unit":"percent_cashback"},"ott":{"rate":5,"unit":"percent_cashback"},"other":{"rate":1,"unit":"percent_cashback"}}'::jsonb, null, null, 'none', null, null, false, null, null, null, null, null, false, false, 3.5, null, '10% cashback on Swiggy (food, Instamart, Dineout). 5% on OTT platforms. 1% on other spends.', array['10% cashback on Swiggy food, Instamart, and Dineout', '5% cashback on OTT platforms', '1% cashback on all other spends', 'Annual fee waiver on INR 2L spend']::text[], array['Best rewards limited to Swiggy platform', 'No lounge access', 'No fuel surcharge waiver']::text[], array['dining', 'entertainment', 'groceries']::text[], 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/swiggy-credit-card', true, 86, 'catalog_import', now(), '{}'::jsonb),
  ('onecard', 'Federal Bank', 'OneCard Metal Credit Card', 'visa', 'rewards', 'classic', null, 0, 0, null, 0, 360000, null, 360000, 700, 700, 18, 60, null, null, 0, '{"top_2_categories":{"rate":5,"unit":"points_per_100"},"other":{"rate":1,"unit":"points_per_100"}}'::jsonb, null, null, 'none', null, null, true, null, null, null, null, null, false, false, 2, null, '5x rewards on top 2 spend categories each month. 1x on all other spends.', array['Lifetime free metal credit card', '5x rewards on your top 2 spend categories automatically', 'EMIs available on all purchases', 'No foreign transaction fee within the OneCard ecosystem']::text[], array['No lounge access', 'Cannot choose reward categories manually', 'App-only management (no branch support)']::text[], array['shopping', 'dining', 'entertainment']::text[], 'https://www.getonecard.app/', true, 84, 'catalog_import', now(), '{}'::jsonb),
  ('slice-super-card', 'IDFC First Bank', 'Slice Super Card', 'mastercard', 'entry_level', 'classic', null, 0, 0, null, 0, null, null, null, null, null, 18, 65, null, null, 2, '{}'::jsonb, null, null, 'none', null, null, false, null, null, null, null, null, false, false, 3.5, null, '2% cashback on all spends. No minimum transation. Instant credit.', array['Lifetime free card with no hidden fees', '2% cashback on all spends with no cap', 'Instant approval and digital-first experience', 'Pay in 3 EMI option on all purchases']::text[], array['Low credit limit for new users', 'No lounge access or premium perks', 'EMI charges apply after billing cycle']::text[], array['shopping', 'dining', 'utilities']::text[], 'https://www.sliceit.com/', true, 76, 'catalog_import', now(), '{}'::jsonb),
  ('jupiter-edge-cred-card', 'Federal Bank', 'Jupiter Edge CSB Bank Credit Card', 'visa', 'entry_level', 'classic', null, 0, 0, null, 0, null, null, null, null, null, 18, 65, null, null, 1, '{}'::jsonb, null, null, 'none', null, null, false, null, null, null, null, null, false, false, 3.5, null, '1% cashback on all spends. Instant issuance via Jupiter app.', array['Lifetime free card', '1% cashback on all transactions', 'Instant virtual card issuance', 'No late payment charges if minimum balance maintained']::text[], array['Very low reward rate of 1%', 'No lounge access', 'No fuel surcharge waiver', 'Limited app ecosystem compared to banks']::text[], array['shopping', 'utilities']::text[], 'https://jupiter.money/', true, 70, 'catalog_import', now(), '{}'::jsonb),
  ('hdfc-regalia', 'HDFC Bank', 'HDFC Regalia Credit Card', 'visa', 'premium', 'signature', null, 2500, 2500, 300000, 2500, 900000, null, 900000, 750, 750, 21, 65, null, null, 0, '{"dining_travel":{"rate":8,"unit":"points_per_100"},"other":{"rate":4,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome vouchers worth ₹2,000 on first spend","points":2000}'::jsonb, null, 'domestic_and_international', '6 domestic + 2 international per year', null, true, null, null, 'Dine out privileges at select partner restaurants with up to 15% off', 5000000, null, false, false, 2, null, '4 reward points per INR 150 on all spends. 2x on dining and travel.', array['Complimentary Priority Pass (2 international visits per year)', '6 domestic lounge visits per year', '2x reward points on dining and travel', 'Annual fee waiver on INR 3L spend']::text[], array['Annual fee of ₹2,500', 'Being phased out in favor of Regalia Gold', 'Limited Priority Pass visits (2 international)']::text[], array['travel', 'dining', 'shopping']::text[], 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-credit-card', true, 88, 'catalog_import', now(), '{}'::jsonb),
  ('idfc-first-select', 'IDFC First Bank', 'IDFC FIRST Select Credit Card', 'visa', 'premium', 'signature', null, 0, 0, null, 0, 600000, null, 600000, 720, 720, 21, 65, null, null, 0, '{"online":{"rate":6,"unit":"points_per_100"},"offline":{"rate":3,"unit":"points_per_100"}}'::jsonb, null, null, 'domestic_only', '4 domestic per year', null, true, null, null, null, null, null, false, false, 0, null, '6x reward points on online spends. 3x on offline. Points never expire.', array['Lifetime free card', '6x reward points on online spends', '3x on offline spends', '4 domestic lounge visits per year']::text[], array['Must maintain IDFC account for lifetime free', 'Limited lounge visits (4 domestic)', 'No concierge service']::text[], array['shopping', 'utilities', 'groceries']::text[], 'https://www.idfcfirstbank.com/credit-card/select', true, 88, 'catalog_import', now(), '{}'::jsonb),
  ('sbi-air-india-signature', 'State Bank of India (SBI)', 'Air India SBI Platinum Credit Card', 'visa', 'travel', 'platinum', null, 1499, 1499, 200000, 1499, 600000, null, 600000, 720, 720, 21, 65, null, null, 0, '{"air_india":{"rate":15,"unit":"points_per_100"},"sbi_merchants":{"rate":5,"unit":"points_per_100"},"other":{"rate":2,"unit":"points_per_100"}}'::jsonb, null, null, 'domestic_only', 'Air India lounges', null, false, null, null, null, 3000000, null, false, false, 3.5, null, '15 Air India miles per INR 100 on Air India. 5 miles on SBI merchant transactions.', array['15 Air India miles per INR 100 on Air India spends', '5 miles per INR 100 on SBI merchant spends', 'Complimentary Air India lounge access', 'Annual fee waiver on INR 2L spend']::text[], array['Miles value only with Air India flights', 'Limited airline partnerships', 'No fuel surcharge waiver']::text[], array['travel']::text[], 'https://www.sbicard.com/en/personal/credit-cards/travel-fuel/air-india-sbi-signature.page', true, 78, 'catalog_import', now(), '{}'::jsonb),
  ('axis-vistara-infinite', 'Axis Bank', 'Club Vistara Axis Bank Infinite Card', 'visa', 'travel', 'infinite', null, 10000, 10000, null, 10000, 1500000, null, 1500000, 780, 780, 21, 65, null, null, 0, '{"vistara":{"rate":10,"unit":"points_per_100"},"other":{"rate":6,"unit":"points_per_100"}}'::jsonb, '{"description":"Complimentary Business Class domestic ticket on activation","points":15000}'::jsonb, '{"annual_15l":{"spend_threshold":1500000,"benefit":"Complimentary Business Class ticket + renewal fee waiver","value":20000}}'::jsonb, 'domestic_and_international', '8 domestic + 6 international per year', null, true, null, null, null, 10000000, null, false, true, 2, null, '10 Club Vistara Points per INR 200 on Vistara. 6 CVP per INR 200 on others.', array['Complimentary Business Class ticket on joining and renewal', '10 CVP per INR 200 on Vistara flights', 'Complimentary lounge access (8 domestic + 6 international per year)', 'Club Vistara Gold membership']::text[], array['Very high annual fee of ₹10,000', 'Vistara merged with Air India (program transition)', 'Club Vistara Gold perks may change']::text[], array['travel']::text[], null, false, 90, 'catalog_import', now(), '{}'::jsonb),
  ('sbi-miles-elite', 'State Bank of India (SBI)', 'SBI Card Miles Elite', 'mastercard', 'travel', 'world', null, 4999, 4999, 500000, 4999, 1200000, null, 1200000, 750, 750, 21, 65, null, null, 0, '{"international_travel":{"rate":20,"unit":"points_per_100"},"other":{"rate":5,"unit":"points_per_100"}}'::jsonb, '{"description":"Welcome miles worth ₹5,000 on first transaction","points":5000}'::jsonb, null, 'domestic_and_international', '12 domestic + 4 international per year', null, true, null, null, null, 10000000, null, false, false, 1.99, null, '20 reward points per INR 100 on international and travel spends. 5x on other spends.', array['20x reward points on international and travel spends', 'Complimentary domestic lounge access (12 per year)', '4 international lounge visits per year', 'Travel insurance and flight delay compensation']::text[], array['Annual fee of ₹4,999', 'Miles have limited transfer partners in India', 'Non-travel redemptions offer poor value']::text[], array['travel', 'dining']::text[], 'https://www.sbicard.com/en/personal/credit-cards/miles/sbi-card-miles-elite.page', true, 84, 'catalog_import', now(), '{}'::jsonb)
on conflict (card_slug) do update set
  bank_name = excluded.bank_name,
  card_name = excluded.card_name,
  card_network = excluded.card_network,
  card_type = excluded.card_type,
  card_variant = excluded.card_variant,
  image_url = excluded.image_url,
  joining_fee = excluded.joining_fee,
  annual_fee = excluded.annual_fee,
  annual_fee_waiver_spend = excluded.annual_fee_waiver_spend,
  renewal_fee = excluded.renewal_fee,
  min_income_salaried = excluded.min_income_salaried,
  min_income_self_employed = excluded.min_income_self_employed,
  min_income_required = excluded.min_income_required,
  min_cibil_score = excluded.min_cibil_score,
  min_credit_score = excluded.min_credit_score,
  min_age = excluded.min_age,
  max_age = excluded.max_age,
  requires_itr = excluded.requires_itr,
  requires_existing_relationship = excluded.requires_existing_relationship,
  reward_rate_default = excluded.reward_rate_default,
  reward_rate_categories = excluded.reward_rate_categories,
  welcome_benefits = excluded.welcome_benefits,
  milestone_benefits = excluded.milestone_benefits,
  lounge_access = excluded.lounge_access,
  lounge_access_details = excluded.lounge_access_details,
  lounge_visits_per_quarter = excluded.lounge_visits_per_quarter,
  fuel_surcharge_waiver = excluded.fuel_surcharge_waiver,
  fuel_surcharge_waiver_cap = excluded.fuel_surcharge_waiver_cap,
  movie_benefits = excluded.movie_benefits,
  dining_benefits = excluded.dining_benefits,
  travel_insurance_cover = excluded.travel_insurance_cover,
  purchase_protection_cover = excluded.purchase_protection_cover,
  golf_access = excluded.golf_access,
  concierge_service = excluded.concierge_service,
  forex_markup = excluded.forex_markup,
  emi_conversion_available = excluded.emi_conversion_available,
  description = excluded.description,
  pros = excluded.pros,
  cons = excluded.cons,
  best_for = excluded.best_for,
  apply_url = excluded.apply_url,
  is_active = excluded.is_active,
  popularity_score = excluded.popularity_score,
  data_source = excluded.data_source,
  data_last_verified_at = now(),
  metadata = '{}'::jsonb,
  updated_at = now();

comment on table public.credit_cards is
  'Canonical CardSense card catalog. Runtime card details must come from this table only.';

commit;

select count(*) as total_cards,
       count(*) filter (where is_active) as active_cards
from public.credit_cards;
